# Generated by the K8Sense release workflow. Do not hand-edit.
#
# A CASK, not a formula, because K8Sense is a GUI application. A formula puts an
# executable on your PATH; a cask installs an .app into /Applications where the
# Dock, Spotlight and Launchpad can find it. Installing a windowed application
# through a formula leaves it invisible to all three.
cask "k8sense" do
  version "0.0.0"

  # One universal build covers Apple Silicon and Intel, so there is a single
  # URL and a single checksum rather than an arch conditional.
  sha256 "0000000000000000000000000000000000000000000000000000000000000000"

  url "https://github.com/k8sense/k8sense/releases/download/v#{version}/k8sense_v#{version}_macos-universal.zip"
  name "K8Sense"
  desc "Native Kubernetes client that tells you what is wrong"
  homepage "https://k8sense.com/"

  livecheck do
    url :url
    strategy :github_latest
  end

  # Wails builds an unsigned bundle, so macOS refuses to open it until the
  # quarantine flag is cleared. `auto_updates false` and this depends_on are
  # honest metadata rather than a workaround; see the caveat below.
  depends_on macos: ">= :high_sierra"

  app "K8Sense.app"

  # Everything K8Sense writes lives under the user's own configuration
  # directory: the recorded cluster history and its retention setting. Removing
  # them on uninstall is the behaviour somebody uninstalling expects, and the
  # data is a local cache of figures rather than anything they authored.
  zap trash: [
    "~/Library/Application Support/K8Sense",
    "~/Library/Saved Application State/com.k8sense.desktop.savedState",
    "~/Library/Preferences/com.k8sense.desktop.plist",
  ]

  caveats <<~EOS
    K8Sense is not yet signed with an Apple Developer ID, so macOS will refuse
    to open it the first time with "K8Sense is damaged and can't be opened".
    It is not damaged — that is Gatekeeper reporting an unsigned download.

    Clear the quarantine flag once:

      xattr -dr com.apple.quarantine /Applications/K8Sense.app

    K8Sense reads your existing kubeconfig and talks only to the clusters it
    names. It sends nothing anywhere else.
  EOS
end
